from os import getenv

SQLALCHEMY_TRACK_MODIFICATIONS = False,
DEBUG = True,
TEST = True,
SECRET_KEY = getenv("SECRECT_KEY"),
SQLALCHEMY_ECHO = False
SQLALCHEMY_DATABASE_URI = getenv("DATABASE_URL")
JWT_ACCESS_LIFESPAN = {'hours': 24}
JWT_REFRESH_LIFESPAN = {'days': 5}